name: Update quay.io/ai-lab images

on:
  schedule: # schedule the job to run at 12 AM daily
   - cron: '0 0 * * *'
  
  workflow_dispatch:

env:
  REGISTRY: quay.io/ai-lab
  CHATBOT_IMAGE_NAME: chatbot
  LLAMACPP_PYTHON_IMAGE_NAME: llamacpp-python
  MISTRAL_MODEL_IMAGE_NAME: mistral-7b-instruct
  MISTRAL_TAG: v0.1.Q4_K_M.gguf
  MISTRAL_MODEL_URL: https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_K_M.gguf

jobs:
  build-and-push-mistral-model-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4.1.1

      # required for multi-arch builds
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build mistral model image
        id: build_mistral_model_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.MISTRAL_MODEL_IMAGE_NAME }}
          tags: latest ${{ env.MISTRAL_TAG }}
          platforms: linux/amd64, linux/arm64
          context: models
          build-args: |
            MODEL_URL=${{ env.MISTRAL_MODEL_URL }}
          containerfiles: ./models/Containerfile

      - name: Login to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push mistral model image
        id: push_mistral_model_image
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build_mistral_model_image.outputs.image }}
          tags: ${{ steps.build_mistral_model_image.outputs.tags }}

  build-and-push-llamacpp-python-base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4.1.1

      # required for multi-arch builds
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build llamacpp-python-base
        id: build_llamacpp_python_base
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.LLAMACPP_PYTHON_IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          context: model_servers/llamacpp_python
          containerfiles: ./model_servers/llamacpp_python/base/Containerfile

      - name: Login to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push llamacpp-python image
        id: push_llamacpp_python
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build_llamacpp_python_base.outputs.image }}
          tags: ${{ steps.build_llamacpp_python_base.outputs.tags }}

  build-and-push-chatbot-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4.1.1

      # required for multi-arch builds
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build chatbot image
        id: build_chatbot_image
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ${{ env.CHATBOT_IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          platforms: linux/amd64, linux/arm64
          containerfiles: ./recipes/natural_language_processing/chatbot/builds/Containerfile
          context: recipes/natural_language_processing/chatbot

      - name: Login to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push chatbot image
        id: push_chatbot_image
        uses: redhat-actions/push-to-registry@v2.8
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build_chatbot_image.outputs.image }}
          tags: ${{ steps.build_chatbot_image.outputs.tags }}
